name: Node.js Package

on:
  push:
    paths-ignore:
    - '**.md'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '!build')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
